name: "tuxedo-systeminfos"
summary: "TUXEDO Systeminfos Script"
description: "Script from TUXEDO Computers to get necessary information of the system for technical support purposes."
git-url: "https://gitlab.com/tuxedocomputers/development/systeminfos-script"
dependencies:
  ["curl, edid-decode, efibootmgr, jq, lm-sensors, mesa-utils, nvme-cli, zip"]
ci_upload_dir: "tuxedo-systeminfos"

changelog:
  - version: "20251103.1"
    author: "Steven Seifried"
    date: 2025-11-03 08:45:00
    entries:
      - "Use simple-package-creator for packaging"
