#!/bin/sh
set -e

case "$1" in
    remove|purge|disappear)
    ;;

    upgrade|abort-upgrade|abort-install|failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
